### PR TITLE
:truck: Organized md files

### PR DESCRIPTION
**Pull request by Sigmanificient**

### CODE REVIEW

**Comment by MCWertGaming** [comment]
Shouldn't we combine the install instructions and the Readme? Or move it to a wiki page? Or to the contribution guidelines.

**Comment by Sigmanificient** [comment]
> Shouldn't we combine the install instructions and the Readme? Or move it to a wiki page? Or to the contribution guidelines.

I like to use install.md cause it's avoid bloating the readme.

**Comment by MCWertGaming** [comment]
I mean combining both into one is just normal for most GitHub projects. Also what about moving it into a GitHub wiki?

**Comment by Sigmanificient** [comment]
> Also what about moving it into a GitHub wiki?

Well, i never used them before

**Comment by Sigmanificient** [comment]
> I mean combining both into one is just normal for most GitHub projects.

Well i tend to split into multiple readme like `install`, `tests`, ... so it's easy to find sutff you want

**Comment by MCWertGaming** [comment]
I think that we should stick to what's commonly done on GitHub? I mean in the end it doesn't matter but having everything in one page is a lot more efficient that moving over 3 pages in total idk.

**Comment by MCWertGaming** [comment]
When you added the instructions for building using `make` we can merge this one!

**Review by MCWertGaming — APPROVED** [review]
Really nice, thank you!

**Pull request merged**
